language: bash

services:
  - docker

script:
  - docker-compose run --rm node sh -c 'yarn && yarn build'
  - docker-compose run --rm ruby sh -c 'bundle install && jekyll build -s ./app -d _build'
  - ls -1 _build
